# Generated by Django 6.0.6 on 2026-06-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
    ]
